const getQuote = (dayNumber) => {
    return quotes[dayNumber - 2] + "\n" + quoteAuthor[dayNumber - 2];
}

export default getQuote;

const quotes =
    ["Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "Believe you can and you're halfway there.",
        "The only way to do great work is to love what you do.",
        "In the middle of difficulty lies opportunity.",
        "Success is not the key to happiness.Happiness is the key to success.If you love what you are doing, you will be successful.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "The way to get started is to quit talking and begin doing.",
        "Don't watch the clock; do what it does. Keep going.",
        "You are never too old to set another goal or to dream a new dream.",
        "Success is not in what you have, but who you are.",
        "The only place where success comes before work is in the dictionary.",
        "You don't have to be great to start, but you have to start to be great.",
        "Believe in yourself and all that you are.Know that there is something inside you that is greater than any obstacle.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Success is not the result of spontaneous combustion.You must set yourself on fire.",
        "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream big and dare to fail.",
        "I am not a product of my circumstances.I am a product of my decisions.",
        "Your attitude, not your aptitude, will determine your altitude.",
        "You miss 100 % of the shots you don't take.",
        "The best way to predict the future is to create it.",
        "The only person you should try to be better than is the person you were yesterday.",
        "The road to success and the road to failure are almost exactly the same.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "The difference between ordinary and extraordinary is that little extra.",
        "You must expect great things of yourself before you can do them.",
        "Hardships often prepare ordinary people for an extraordinary destiny.",
        "Opportunities don't happen. You create them.",
        "The only way to achieve the impossible is to believe it is possible.",
        "Strive not to be a success, but rather to be of value.",
        "Keep your face always toward the sunshine—and shadows will fall behind you.",
        "Do not wait to strike till the iron is hot, but make it hot by striking.",
        "    Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
        "You never know how strong you are until being strong is your only choice.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "When you feel like quitting, think about why you started.",
        "Life is 10 % what happens to us and 90 % how we react to it.",
        "    It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.",
        "The only person you should try to be better than is the person you were yesterday.",
        "Success is not just about the destination, it's about the journey.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "    Don't wait for opportunity, create it.",
        "The only way to do great work is to love what you do.",
        "    Don't stop when you're tired.Stop when you're done.",
        "Success is not the key to happiness.Happiness is the key to success.If you love what you are doing, you will be successful.",
        "The only place where success comes before work is in the dictionary.",
        "    Don't watch the clock; do what it does. Keep going.",
        "Believe you can and you're halfway there.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Dream big and dare to fail.",
        "You are never too old to set another goal or to dream a new dream.",
        "The only way to achieve the impossible is to believe it is possible.",
        "Believe in yourself and all that you are.Know that there is something inside you that is greater than any obstacle.",
        "The best way to predict the future is to create it.",
        "Success is not the result of spontaneous combustion.You must set yourself on fire.",
        "You miss 100 % of the shots you don't take.",
        "Success is not in what you have, but who you are.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "In the middle of difficulty lies opportunity.",
        "The only way to do great work is to love what you do.",
        "    Don't watch the clock; do what it does. Keep going.",
        "Believe you can and you're halfway there.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "Success is not the result of spontaneous combustion.You must set yourself on fire.",
        "You miss 100 % of the shots you don't take.",
        "The best way to predict the future is to create it.",
        "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream big and dare to fail.",
        "I am not a product of my circumstances.I am a product of my decisions.",
        "Your attitude, not your aptitude, will determine your altitude.",
        "You miss 100 % of the shots you don't take.",
        "The best way to predict the future is to create it.",
        "Success is not the result of spontaneous combustion.You must set yourself on fire.",
        "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream big and dare to fail.",
        "I am not a product of my circumstances.I am a product of my decisions.",
        "Your attitude, not your aptitude, will determine your altitude.",
        "You miss 100 % of the shots you don't take.",
        "The best way to predict the future is to create it.",
        "Success is not the result of spontaneous combustion.You must set yourself on fire.",
        "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream big and dare to fail.",
        "I am not a product of my circumstances.I am a product of my decisions.",
        "Your attitude, not your aptitude, will determine your altitude.",
        "You miss 100 % of the shots you don't take.",
        "The best way to predict the future is to create it.",
        "Success is not the result of spontaneous combustion.You must set yourself on fire.",
        "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Dream big and dare to fail.",
        "I am not a product of my circumstances.I am a product of my decisions.",
        "Your attitude, not your aptitude, will determine your altitude.",
        "You miss 100 % of the shots you don't take.",
        "The best way to predict the future is to create it.",
        "Success is not the result of spontaneous combustion.You must set yourself on fire.",
        "Challenges are what make life interesting and overcoming them is what makes life meaningful."];

const quoteAuthor = ["Winston Churchill",
    "Theodore Roosevelt",
    "Steve Jobs",
    "Albert Einstein",
    "Albert Schweitzer",
    "Franklin D.Roosevelt",
    "Walt Disney",
    "Sam Levenson",
    "C.S.Lewis",
    "Bo Bennett",
    "Vidal Sassoon",
    "Zig Ziglar",
    "Christian D.Larson",
    "Eleanor Roosevelt",
    "Arnold H.Glasow",
    "Joshua J.Marine",
    "Unknown",
    "Norman Vaughan",
    "Stephen Covey",
    "Zig Ziglar",
    "Wayne Gretzky",
    "Peter Drucker",
    "Unknown",
    "Colin R.Davis",
    "Winston Churchill",
    "Jimmy Johnson",
    "Michael Jordan",
    "C.S.Lewis",
    "Chris Grosser",
    "Charles Kingsleigh(Alice in Wonderland)",
    "Albert Einstein",
    "Walt Whitman",
    "William Butler Yeats",
    "Roy T.Bennett",
    "Bob Marley",
    "Franklin D.Roosevelt",
    "Unknown",
    "Charles R.Swindoll",
    "Rocky Balboa",
    "Unknown",
    "Unknown",
    "Franklin D.Roosevelt",
    "Unknown",
    "Steve Jobs",
    "Unknown",
    "Albert Schweitzer",
    "Vidal Sassoon",
    "Sam Levenson",
    "Theodore Roosevelt",
    "Eleanor Roosevelt",
    "Norman Vaughan",
    "C.S.Lewis",
    "Charles Kingsleigh(Alice in Wonderland)",
    "Christian D.Larson",
    "Peter Drucker",
    "Arnold H.Glasow",
    "Wayne Gretzky",
    "Bo Bennett",
    "Franklin D.Roosevelt",
    "Albert Einstein",
    "Steve Jobs",
    "Sam Levenson",
    "Theodore Roosevelt",
    "Eleanor Roosevelt",
    "Arnold H.Glasow",
    "Wayne Gretzky",
    "Peter Drucker",
    "Joshua J.Marine",
    "Unknown",
    "Norman Vaughan",
    "Stephen Covey",
    "Zig Ziglar",
    "Wayne Gretzky",
    "Peter Drucker",
    "Arnold H.Glasow",
    "Joshua J.Marine",
    "Unknown",
    "Norman Vaughan",
    "Stephen Covey",
    "Zig Ziglar",
    "Wayne Gretzky",
    "Peter Drucker",
    "Arnold H.Glasow",
    "Joshua J.Marine",
    "Unknown",
    "Norman Vaughan",
    "Stephen Covey",
    "Zig Ziglar",
    "Wayne Gretzky",
    "Peter Drucker",
    "Arnold H.Glasow",
    "Joshua J.Marine",
    "Unknown",
    "Norman Vaughan",
    "Stephen Covey",
    "Zig Ziglar",
    "Wayne Gretzky",
    "Peter Drucker",
    "Arnold H.Glasow",
    "Joshua J.Marine"];